/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import java.io.File;
import java.util.Arrays;

import javax.servlet.ServletException;

import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.startup.Tomcat;
import org.glassfish.jersey.server.ResourceConfig;
import org.glassfish.jersey.servlet.ServletContainer;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) throws Exception	 {
    	System.out.println(Arrays.toString(args));
        new Library().start();
    }

    public void start() throws ServletException, LifecycleException {

        Tomcat tomcat = new Tomcat();
        tomcat.setPort(9080);

        Context context = tomcat.addWebapp("/", new File(".").getAbsolutePath());

        Tomcat.addServlet(context, "jersey-container-servlet", resourceConfig());
        context.addServletMapping("/*", "jersey-container-servlet");

        tomcat.start();	
        tomcat.getServer().await();
    }

    private ServletContainer resourceConfig() {
        return new ServletContainer(new ResourceConfig(new ResourceLoader().getClasses()));
    }
}
